const KEY='life_rpg_roadmap_v4',today=()=>new Date().toISOString().slice(0,10);
const QUOTES=[["Build quietly. Let your consistency become the loudest thing about you.", "Discipline"], ["A stronger body begins with one honest workout, not a perfect week.", "Strength"], ["Your future self is watching what you choose to repeat today.", "Long-term growth"], ["Faith is not separate from progress; it gives progress direction.", "Faith"], ["Rest is part of the plan. Recovery is how effort becomes strength.", "Sleep"], ["Check the numbers, learn the lesson, then keep moving without panic.", "Finance"], ["Confidence grows when you keep promises that nobody else sees.", "Confidence"], ["Career progress is built in quiet moments of preparation.", "Career"], ["Your family will remember your presence more than your productivity.", "Relationships"], ["You do not need to rush your transformation. You only need to continue it.", "Patience"], ["Train for the body you want, but live like the man you want to become.", "Identity"], ["One good decision can change the tone of an entire day.", "Momentum"], ["Protect your sleep like it protects everything else.", "Recovery"], ["Real wealth is built by patience, restraint, and clear thinking.", "Wealth"], ["Knowledge compounds when you return to it every day.", "Learning"], ["Take care of your appearance, but build a life that carries the confidence.", "Self-respect"], ["Discipline is choosing what matters most over what feels easiest now.", "Discipline"], ["Your progress does not disappear just because today feels slower.", "Resilience"], ["A calm mind makes better decisions than an urgent one.", "Clarity"], ["Small acts of worship can steady an entire life.", "Faith"], ["Strength is not only what you lift; it is what you refuse to give up on.", "Strength"], ["You are allowed to grow without proving it to everyone.", "Peace"], ["Consistency turns ordinary days into an uncommon life.", "Consistency"], ["Your goals deserve a version of you that sleeps, plans, and follows through.", "Balance"], ["Check your stocks, then return to building the life behind the portfolio.", "Finance"], ["Confidence is quieter than comparison and stronger than attention.", "Confidence"], ["The body changes when the routine becomes normal.", "Fitness"], ["A better life is usually built before it is noticed.", "Quiet progress"], ["Protect your attention. It becomes your future.", "Focus"], ["Keep becoming someone your younger self would feel safe with.", "Character"], ["Discipline today. Freedom tomorrow.", "Core principle"]];
const baseStats={Strength:20,Endurance:18,Intelligence:22,Discipline:20,Charisma:18,Confidence:17,Faith:20,Health:22,Energy:20,Sleep:15,Nutrition:18,Wealth:15,Career:16,Knowledge:20,Relationships:18,Intimacy:15};
const meta={Strength:['💪','#c76555'],Endurance:['🏃','#d88c57'],Intelligence:['🧠','#7594b6'],Discipline:['🎯','#bda05c'],Charisma:['💬','#bd789c'],Confidence:['😎','#6da6aa'],Faith:['🕌','#789d7e'],Health:['❤️','#cd7474'],Energy:['⚡','#c7a55b'],Sleep:['🌙','#8b82ad'],Nutrition:['🍎','#84a871'],Wealth:['💰','#b99a58'],Career:['💼','#6d9bb2'],Knowledge:['📚','#8c7daa'],Relationships:['🤝','#b77f9d'],Intimacy:['🔒','#9d7f91']};
const baseQuests=[['workout','Complete a workout',30,'Strength'],['water','Drink enough water',15,'Health'],['read','Read or study',20,'Knowledge'],['faith','Complete faith practice',20,'Faith'],['stocks','Check your stocks',15,'Wealth'],['family','Connect with family or friends',15,'Relationships'],['sleep','Protect your sleep tonight',15,'Sleep']].map(x=>({id:x[0],text:x[1],xp:x[2],stat:x[3],done:false}));
const fresh=()=>({name:'Mumen',pin:'8965',level:1,xp:0,streak:0,lastActive:null,lastReset:today(),stats:{...baseStats},quests:baseQuests,custom:[],sleep:{hours:0,score:0},finance:{portfolio:0,savings:0,stocks:false},gym:{bench:0,squat:0,deadlift:0,weight:0},journals:[],intimacy:{confidence:50,connection:50,communication:50,satisfaction:50,note:''},partners:[]});
let s=(()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return x?{...fresh(),...x,stats:{...baseStats,...x.stats},partners:x.partners||[]}:fresh()}catch{return fresh()}})();
const save=()=>localStorage.setItem(KEY,JSON.stringify(s));
let failedAttempts=0,lockTimer=null,editingPartnerId=null;
function startAutoLock(){clearTimeout(lockTimer);lockTimer=setTimeout(lockApp,5*60*1000)}
['click','touchstart','keydown'].forEach(evt=>document.addEventListener(evt,()=>{if(!app.hidden)startAutoLock()},{passive:true}));
function lockApp(){app.hidden=true;lockScreen.style.display='grid';pinInput.value='';lockMessage.textContent='';clearTimeout(lockTimer)}
function unlockApp(){if(pinInput.value===s.pin){failedAttempts=0;lockScreen.style.display='none';app.hidden=false;pinInput.value='';render();startAutoLock()}else{failedAttempts++;lockMessage.textContent=failedAttempts>=3?'Incorrect code. Please wait a moment and try again.':'Incorrect code.';if(failedAttempts>=3){unlockAppBtn.disabled=true;setTimeout(()=>{unlockAppBtn.disabled=false;failedAttempts=0;lockMessage.textContent=''},10000)}}}
unlockAppBtn.onclick=unlockApp;pinInput.onkeydown=e=>{if(e.key==='Enter')unlockApp()};togglePin.onclick=()=>{pinInput.type=pinInput.type==='password'?'text':'password';togglePin.textContent=pinInput.type==='password'?'Show':'Hide'};lockNowBtn.onclick=lockApp;
function resetDay(){if(s.lastReset!==today()){[...s.quests,...s.custom].forEach(q=>q.done=false);s.finance.stocks=false;s.lastReset=today();save()}}
function title(){return s.level>=20?'Life Architect':s.level>=15?'Ascendant':s.level>=12?'The Disciplined':s.level>=7?'Rising Hero':s.level>=3?'On the Grind':'New Adventurer'}
function updateStreak(){if(s.lastActive===today())return;const d=new Date();d.setDate(d.getDate()-1);s.streak=s.lastActive===d.toISOString().slice(0,10)?s.streak+1:1;s.lastActive=today()}
function gain(xp,stat){const oldLevel=s.level;s.xp+=xp;while(s.xp>=s.level*100){s.xp-=s.level*100;s.level++}if(stat)s.stats[stat]=Math.min(100,(s.stats[stat]||0)+2);updateStreak();save();render();if(s.level>oldLevel)showLevelUp()}
function showLevelUp(){levelEffectText.textContent='LEVEL UP ✦';avatarPanel.animate([{transform:'scale(1)'},{transform:'scale(1.02)'},{transform:'scale(1)'}],{duration:900});setTimeout(()=>levelEffectText.textContent=evolutionData().effect,1500)}
function setQuote(){const d=new Date();const start=new Date(d.getFullYear(),0,0);const day=Math.floor((d-start)/86400000);const q=QUOTES[day%QUOTES.length];dailyQuote.textContent='“'+q[0]+'”';quoteTheme.textContent=q[1]}
function evolutionData(){
 const l=s.level;
 if(l>=20)return{stage:5,name:'Life Architect',next:'Maximum current evolution reached',effect:'MASTER AURA',shirt:['#5f6f86','#8d9caf'],torso:'M54 319c6-118 28-181 76-181s70 63 76 181z',arm:29,hair:'M82 70c4-45 27-62 51-62 36 0 55 25 55 62-16-18-33-26-55-26-20 0-35 9-51 26z',watch:1,necklace:1};
 if(l>=15)return{stage:5,name:'Ascendant Form',next:'Next major evolution at Level 20',effect:'ASCENDANT GLOW',shirt:['#7d6685','#aa8aae'],torso:'M56 319c5-116 27-178 74-178s69 62 74 178z',arm:28,hair:'M82 70c4-45 27-62 51-62 36 0 55 25 55 62-16-18-33-26-55-26-20 0-35 9-51 26z',watch:1,necklace:1};
 if(l>=10)return{stage:4,name:'Athletic Form',next:'Next major evolution at Level 15',effect:'FOCUSED AURA',shirt:['#6c8794','#91aab5'],torso:'M58 319c5-114 26-175 72-175s67 61 72 175z',arm:27,hair:'M83 70c4-44 26-60 50-60 35 0 54 24 54 60-15-18-32-25-54-25-19 0-34 8-50 25z',watch:1,necklace:1};
 if(l>=5)return{stage:3,name:'Developing Form',next:'Next major evolution at Level 10',effect:'MOMENTUM',shirt:['#7f986f','#a4b692'],torso:'M60 319c5-112 25-171 70-171s65 59 70 171z',arm:25,hair:'M84 70c4-43 25-59 49-59 34 0 53 23 53 59-15-17-31-24-53-24-19 0-33 8-49 24z',watch:1,necklace:0};
 if(l>=2)return{stage:2,name:'Awakening',next:'Next major evolution at Level 5',effect:'AWAKENING',shirt:['#b27b5c','#cf9b74'],torso:'M62 319c4-110 24-168 68-168s64 58 68 168z',arm:23,hair:'M84 70c4-42 25-58 49-58 33 0 52 23 52 58-15-17-31-24-52-24-18 0-33 8-49 24z',watch:0,necklace:0};
 return{stage:1,name:'Foundation',next:'Next visual upgrade at Level 2',effect:'FOUNDATION',shirt:['#b97852','#d5a078'],torso:'M64 319c4-108 23-174 66-174s62 66 66 174z',arm:22,hair:'M84 70c4-42 26-58 49-58 33 0 52 24 52 58-15-17-31-24-52-24-19 0-33 8-49 24z',watch:0,necklace:0};
}
function applyEvolution(){
 const e=evolutionData();avatarPanel.className='avatar-panel stage-'+e.stage;evolutionName.textContent=e.name;nextEvolution.textContent=e.next;levelEffectText.textContent=e.effect;shirtStart.setAttribute('stop-color',e.shirt[0]);shirtEnd.setAttribute('stop-color',e.shirt[1]);torsoPath.setAttribute('d',e.torso);leftArm.setAttribute('stroke-width',e.arm);rightArm.setAttribute('stroke-width',e.arm);hairPath.setAttribute('d',e.hair);watch.setAttribute('opacity',e.watch);necklace.setAttribute('opacity',e.necklace);
}
function render(){resetDay();setQuote();applyEvolution();welcome.textContent=`Welcome back, ${s.name}`;playerName.textContent=s.name;level.textContent=s.level;playerTitle.textContent=title();xpText.textContent=`${s.xp} / ${s.level*100} XP`;xpBar.style.width=`${s.xp/(s.level*100)*100}%`;streak.textContent=s.streak;renderQuests();renderStats();renderQuick();renderSleep();renderFinance();renderGym();renderAchievements();renderJournal();renderPrivate();renderPartners()}
function renderQuests(){questList.innerHTML='';[...s.quests,...s.custom].forEach(q=>{const l=document.createElement('label');l.className='quest '+(q.done?'done':'');l.innerHTML=`<input type=checkbox ${q.done?'checked':''}><div><b>${q.text}</b><small>${q.stat} progress</small></div><em>+${q.xp} XP</em>`;l.querySelector('input').onchange=e=>{if(e.target.checked&&!q.done){q.done=true;if(q.id==='stocks')s.finance.stocks=true;gain(q.xp,q.stat)}else{q.done=false;save();render()}};questList.appendChild(l)})}
function renderStats(){statsGrid.innerHTML='';Object.entries(s.stats).forEach(([n,v])=>{const [ic,c]=meta[n];const d=document.createElement('div');d.className='stat';d.style.setProperty('--c',c);d.innerHTML=`<div class=stat-top><span>${ic} ${n}</span><span>${v}</span></div><div class=segments>${Array.from({length:10},(_,i)=>`<i class='${i<Math.round(v/10)?'on':''}'></i>`).join('')}</div>`;statsGrid.appendChild(d)})}
function renderQuick(){quickGrid.innerHTML='';[['🏋️ Workout','Strength',25],['📚 Study','Knowledge',20],['🕌 Faith','Faith',20],['🍎 Nutrition','Nutrition',15],['💼 Career','Career',20],['❤️ Relationships','Relationships',15],['💰 Finance','Wealth',15],['🧘 Recovery','Health',15]].forEach(([t,st,x])=>{const b=document.createElement('button');b.textContent=t;b.onclick=()=>gain(x,st);quickGrid.appendChild(b)})}
function renderSleep(){sleepBar.style.width=s.sleep.score+'%';sleepScore.textContent=s.sleep.score+'%'}
function renderFinance(){stocksCheck.checked=s.finance.stocks;portfolioInput.value=s.finance.portfolio||'';savingsInput.value=s.finance.savings||''}
function renderGym(){benchInput.value=s.gym.bench||'';squatInput.value=s.gym.squat||'';deadliftInput.value=s.gym.deadlift||'';weightInput.value=s.gym.weight||''}
function renderAchievements(){const a=[['🏆 First Step','Reach level 2',s.level>=2],['🔥 On Fire','Reach a 7-day streak',s.streak>=7],['🏋️ Gym Rat','Log a 200 lb lift',Math.max(s.gym.bench,s.gym.squat,s.gym.deadlift)>=200],['📈 Investor','Check stocks and enter a portfolio',s.finance.stocks&&s.finance.portfolio>0],['📖 Bookworm','Reach 40 Knowledge',s.stats.Knowledge>=40],['🛡️ Disciplined','Reach 50 Discipline',s.stats.Discipline>=50],['✨ Evolved','Reach Level 5',s.level>=5],['🌟 Ascendant','Reach Level 15',s.level>=15]];achievementList.innerHTML=a.map(x=>`<div class='badge ${x[2]?'':'locked'}'><b>${x[0]}</b><small>${x[1]}</small></div>`).join('')}
function renderJournal(){journalList.innerHTML=s.journals.map(j=>`<div class=journal-entry><b>${j.mood}</b><small>${j.date}</small><div>${j.text}</div></div>`).join('')}
function renderPrivate(){['confidence','connection','communication','satisfaction'].forEach(k=>{document.getElementById(k).value=s.intimacy[k];document.getElementById(k+'Out').textContent=s.intimacy[k]});privateNote.value=s.intimacy.note||''}
function renderPartners(){
 const included=s.partners.filter(p=>p.include).length;partnerCount.textContent=included;
 partnerList.innerHTML=s.partners.length?s.partners.map(p=>`<div class=partner-entry><div class=entry-head><div><b>${escapeHtml(p.name||'Unnamed')}</b><small>Age ${p.age} · ${escapeHtml(p.type)} · ${escapeHtml(p.status)}</small></div><span>${p.include?'Included':'Excluded'}</span></div>${p.start||p.end?`<small>${p.start||'—'} to ${p.end||'—'}</small>`:''}${p.description?`<p>${escapeHtml(p.description)}</p>`:''}<div class=partner-actions><button class=edit onclick="editPartner('${p.id}')">Edit</button><button class=delete onclick="deletePartner('${p.id}')">Delete</button></div></div>`).join(''):'<p class=privacy-note>No private entries yet.</p>'
}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
questForm.onsubmit=e=>{e.preventDefault();const t=questInput.value.trim();if(!t)return;s.custom.push({id:'c'+Date.now(),text:t,xp:15,stat:'Discipline',done:false});questInput.value='';save();render()}
saveSleepBtn.onclick=()=>{const h=+sleepHours.value||0,q=+sleepQuality.value;s.sleep={hours:h,score:Math.max(0,Math.min(100,Math.round(h/8*100*q)))};gain(20,'Sleep')}
stocksCheck.onchange=e=>{s.finance.stocks=e.target.checked;const q=s.quests.find(x=>x.id==='stocks');if(e.target.checked&&q&&!q.done){q.done=true;gain(q.xp,q.stat)}else{save();render()}}
saveFinanceBtn.onclick=()=>{s.finance.portfolio=+portfolioInput.value||0;s.finance.savings=+savingsInput.value||0;gain(20,'Wealth')}
saveGymBtn.onclick=()=>{s.gym={bench:+benchInput.value||0,squat:+squatInput.value||0,deadlift:+deadliftInput.value||0,weight:+weightInput.value||0};gain(25,'Strength')}
saveJournalBtn.onclick=()=>{const t=journalText.value.trim();if(!t)return;s.journals.unshift({mood:moodSelect.value,text:t,date:new Date().toLocaleDateString()});s.journals=s.journals.slice(0,20);journalText.value='';gain(10,'Confidence')}
togglePrivateBtn.onclick=()=>{privateContent.hidden=!privateContent.hidden;togglePrivateBtn.textContent=privateContent.hidden?'Show':'Hide'}
['confidence','connection','communication','satisfaction'].forEach(k=>document.getElementById(k).oninput=e=>document.getElementById(k+'Out').textContent=e.target.value)
savePrivateBtn.onclick=()=>{['confidence','connection','communication','satisfaction'].forEach(k=>s.intimacy[k]=+document.getElementById(k).value);s.intimacy.note=privateNote.value;s.stats.Intimacy=Math.round((s.intimacy.confidence+s.intimacy.connection+s.intimacy.communication+s.intimacy.satisfaction)/4);gain(10,'Confidence')}
function clearPartnerForm(){partnerName.value='';partnerAge.value='';partnerType.value='Relationship';partnerStatus.value='Past';partnerStart.value='';partnerEnd.value='';partnerDescription.value='';includeCount.checked=true;editingPartnerId=null;savePartnerBtn.textContent='Add private entry'}
savePartnerBtn.onclick=()=>{const age=+partnerAge.value;if(!partnerName.value.trim())return alert('Enter a name or nickname.');if(!age||age<18)return alert('This log is for adults age 18 and older only.');const entry={id:editingPartnerId||'p'+Date.now(),name:partnerName.value.trim(),age,type:partnerType.value,status:partnerStatus.value,start:partnerStart.value,end:partnerEnd.value,description:partnerDescription.value.trim(),include:includeCount.checked};if(editingPartnerId){const i=s.partners.findIndex(p=>p.id===editingPartnerId);s.partners[i]=entry}else s.partners.unshift(entry);save();clearPartnerForm();renderPartners()}
window.editPartner=id=>{const p=s.partners.find(x=>x.id===id);if(!p)return;editingPartnerId=id;partnerName.value=p.name;partnerAge.value=p.age;partnerType.value=p.type;partnerStatus.value=p.status;partnerStart.value=p.start||'';partnerEnd.value=p.end||'';partnerDescription.value=p.description||'';includeCount.checked=!!p.include;savePartnerBtn.textContent='Save changes';partnerName.scrollIntoView({behavior:'smooth',block:'center'})}
window.deletePartner=id=>{if(confirm('Delete this private entry?')){s.partners=s.partners.filter(p=>p.id!==id);save();renderPartners()}}
settingsBtn.onclick=()=>{nameInput.value=s.name;pinSetting.value=s.pin;settingsDialog.showModal()};closeSettingsBtn.onclick=()=>settingsDialog.close();saveSettingsBtn.onclick=()=>{s.name=nameInput.value.trim()||'Player';if(/^\d{4}$/.test(pinSetting.value))s.pin=pinSetting.value;else return alert('Use exactly 4 digits for the access code.');save();settingsDialog.close();render()};resetBtn.onclick=()=>{if(confirm('Delete all saved app data?')){s=fresh();save();settingsDialog.close();render();lockApp()}}
editStatsBtn.onclick=()=>{statInputs.innerHTML='';Object.entries(s.stats).forEach(([n,v])=>{const l=document.createElement('label');l.className='stat-input';l.innerHTML=`<span>${n}</span><input data-stat='${n}' type=number min=0 max=100 value='${v}'>`;statInputs.appendChild(l)});statsDialog.showModal()};closeStatsBtn.onclick=()=>statsDialog.close();saveStatsBtn.onclick=()=>{document.querySelectorAll('#statInputs input').forEach(i=>s.stats[i.dataset.stat]=Math.max(0,Math.min(100,+i.value||0)));save();statsDialog.close();render()}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));
lockApp();
