const K='life_rpg_working_v1',today=()=>new Date().toISOString().slice(0,10);
const baseStats={Strength:20,Endurance:18,Intelligence:22,Discipline:20,Charisma:18,Confidence:17,Faith:20,Health:22,Energy:20,Sleep:15,Nutrition:18,Wealth:15,Career:16,Knowledge:20,Relationships:18,Intimacy:15};
const meta={Strength:['💪','#ef6355'],Endurance:['🏃','#f28b3c'],Intelligence:['🧠','#4d91e8'],Discipline:['🎯','#d6aa36'],Charisma:['💬','#dd62b9'],Confidence:['😎','#46bfd0'],Faith:['🕌','#48ac68'],Health:['❤️','#ef5c70'],Energy:['⚡','#efbd3e'],Sleep:['🌙','#8c69dc'],Nutrition:['🍎','#6ac052'],Wealth:['💰','#d2a73f'],Career:['💼','#4aa4d4'],Knowledge:['📚','#8966cd'],Relationships:['🤝','#d16faf'],Intimacy:['🔒','#9a718f']};
const baseQuests=[['workout','Complete a workout',30,'Strength'],['water','Drink enough water',15,'Health'],['read','Read or study',20,'Knowledge'],['faith','Complete faith practice',20,'Faith'],['stocks','Check your stocks',15,'Wealth'],['family','Connect with family or friends',15,'Relationships']].map(x=>({id:x[0],text:x[1],xp:x[2],stat:x[3],done:false}));
const fresh=()=>({name:'Mumen',level:1,xp:0,streak:0,lastActive:null,lastReset:today(),stats:{...baseStats},quests:baseQuests,custom:[],sleep:{hours:0,score:0},finance:{portfolio:0,savings:0,stocks:false},gym:{bench:0,squat:0,deadlift:0,weight:0},journals:[],intimacy:{confidence:50,connection:50,communication:50,satisfaction:50,note:''}});
let s=(()=>{try{const x=JSON.parse(localStorage.getItem(K)||'null');return x?{...fresh(),...x,stats:{...baseStats,...x.stats}}:fresh()}catch{return fresh()}})();
const save=()=>localStorage.setItem(K,JSON.stringify(s));
function resetDay(){if(s.lastReset!==today()){[...s.quests,...s.custom].forEach(q=>q.done=false);s.finance.stocks=false;s.lastReset=today();save()}}
function title(){return s.level>=12?'The Disciplined':s.level>=7?'Rising Hero':s.level>=3?'On the Grind':'New Adventurer'}
function updateStreak(){if(s.lastActive===today())return;const d=new Date();d.setDate(d.getDate()-1);s.streak=s.lastActive===d.toISOString().slice(0,10)?s.streak+1:1;s.lastActive=today()}
function gain(xp,stat,msg){s.xp+=xp;while(s.xp>=s.level*100){s.xp-=s.level*100;s.level++}if(stat)s.stats[stat]=Math.min(100,(s.stats[stat]||0)+2);updateStreak();save();render()}
function render(){resetDay();hello.textContent=`Welcome back, ${s.name}`;name.textContent=s.name;level.textContent=s.level;titleEl.textContent=title();xpText.textContent=`${s.xp} / ${s.level*100} XP`;xpBar.style.width=`${s.xp/(s.level*100)*100}%`;streak.textContent=s.streak;renderQuests();renderStats();renderQuick();renderSleep();renderMoney();renderGym();renderAchievements();renderJournal();renderPrivate()}
const titleEl=document.getElementById('title');
function renderQuests(){quests.innerHTML='';[...s.quests,...s.custom].forEach(q=>{const l=document.createElement('label');l.className='quest '+(q.done?'done':'');l.innerHTML=`<input type=checkbox ${q.done?'checked':''}><div><b>${q.text}</b><small>${q.stat} progress</small></div><em>+${q.xp} XP</em>`;l.querySelector('input').onchange=e=>{if(e.target.checked&&!q.done){q.done=true;if(q.id==='stocks')s.finance.stocks=true;gain(q.xp,q.stat)}else{q.done=false;save();render()}};quests.appendChild(l)})}
function renderStats(){stats.innerHTML='';Object.entries(s.stats).forEach(([n,v])=>{const [ic,c]=meta[n];const d=document.createElement('div');d.className='stat';d.style.setProperty('--c',c);d.innerHTML=`<div class=statTop><span>${ic} ${n}</span><span>${v}</span></div><div class=segments>${Array.from({length:10},(_,i)=>`<i class='${i<Math.round(v/10)?'on':''}'></i>`).join('')}</div>`;stats.appendChild(d)})}
function renderQuick(){quick.innerHTML='';[['🏋️ Workout','Strength',25],['📚 Study','Knowledge',20],['🕌 Faith','Faith',20],['🍎 Nutrition','Nutrition',15],['💼 Career','Career',20],['❤️ Relationships','Relationships',15],['💰 Finance','Wealth',15],['🧘 Recovery','Health',15]].forEach(([t,st,x])=>{const b=document.createElement('button');b.textContent=t;b.onclick=()=>gain(x,st);quick.appendChild(b)})}
function renderSleep(){sleepBar.style.width=s.sleep.score+'%';sleepScore.textContent=s.sleep.score+'%'}
function renderMoney(){stocks.checked=s.finance.stocks;portfolio.value=s.finance.portfolio||'';savings.value=s.finance.savings||''}
function renderGym(){bench.value=s.gym.bench||'';squat.value=s.gym.squat||'';deadlift.value=s.gym.deadlift||'';weight.value=s.gym.weight||''}
function renderAchievements(){const a=[['🏆 First Step','Reach level 2',s.level>=2],['🔥 On Fire','Reach a 7-day streak',s.streak>=7],['🏋️ Gym Rat','Log a 200 lb lift',Math.max(s.gym.bench,s.gym.squat,s.gym.deadlift)>=200],['📈 Investor','Check stocks and enter a portfolio',s.finance.stocks&&s.finance.portfolio>0],['📖 Bookworm','Reach 40 Knowledge',s.stats.Knowledge>=40],['🛡️ Disciplined','Reach 50 Discipline',s.stats.Discipline>=50]];achievements.innerHTML=a.map(x=>`<div class='badge ${x[2]?'':'locked'}'><b>${x[0]}</b><small>${x[1]}</small></div>`).join('')}
function renderJournal(){journalList.innerHTML=s.journals.map(j=>`<div class=journalEntry><b>${j.mood}</b><small>${j.date}</small><div>${j.text}</div></div>`).join('')}
function renderPrivate(){['confidence','connection','communication','satisfaction'].forEach(k=>{document.getElementById(k).value=s.intimacy[k];document.getElementById(k+'Out').textContent=s.intimacy[k]});privateNote.value=s.intimacy.note||''}
addQuest.onsubmit=e=>{e.preventDefault();const t=questName.value.trim();if(!t)return;s.custom.push({id:'c'+Date.now(),text:t,xp:15,stat:'Discipline',done:false});questName.value='';save();render()}
logSleep.onclick=()=>{const h=+sleepHours.value||0,q=+sleepQuality.value;s.sleep={hours:h,score:Math.max(0,Math.min(100,Math.round(h/8*100*q)))};gain(20,'Sleep')}
stocks.onchange=e=>{s.finance.stocks=e.target.checked;const q=s.quests.find(x=>x.id==='stocks');if(e.target.checked&&q&&!q.done){q.done=true;gain(q.xp,q.stat)}else{save();render()}}
saveMoney.onclick=()=>{s.finance.portfolio=+portfolio.value||0;s.finance.savings=+savings.value||0;gain(20,'Wealth')}
saveGym.onclick=()=>{s.gym={bench:+bench.value||0,squat:+squat.value||0,deadlift:+deadlift.value||0,weight:+weight.value||0};gain(25,'Strength')}
saveJournal.onclick=()=>{const t=journal.value.trim();if(!t)return;s.journals.unshift({mood:mood.value,text:t,date:new Date().toLocaleDateString()});s.journals=s.journals.slice(0,20);journal.value='';gain(10,'Confidence')}
showPrivate.onclick=()=>{private.hidden=!private.hidden;showPrivate.textContent=private.hidden?'Show':'Hide'}
['confidence','connection','communication','satisfaction'].forEach(k=>document.getElementById(k).oninput=e=>document.getElementById(k+'Out').textContent=e.target.value)
savePrivate.onclick=()=>{['confidence','connection','communication','satisfaction'].forEach(k=>s.intimacy[k]=+document.getElementById(k).value);s.intimacy.note=privateNote.value;s.stats.Intimacy=Math.round((s.intimacy.confidence+s.intimacy.connection+s.intimacy.communication+s.intimacy.satisfaction)/4);gain(10,'Confidence')}
settings.onclick=()=>{nameInput.value=s.name;settingsDialog.showModal()};closeSettings.onclick=()=>settingsDialog.close();saveSettings.onclick=()=>{s.name=nameInput.value.trim()||'Player';save();settingsDialog.close();render()};reset.onclick=()=>{if(confirm('Delete all saved app data?')){s=fresh();save();settingsDialog.close();render()}}
editStats.onclick=()=>{statInputs.innerHTML='';Object.entries(s.stats).forEach(([n,v])=>{const l=document.createElement('label');l.className='statInput';l.innerHTML=`<span>${n}</span><input data-stat='${n}' type=number min=0 max=100 value='${v}'>`;statInputs.appendChild(l)});statsDialog.showModal()};closeStats.onclick=()=>statsDialog.close();saveStats.onclick=()=>{document.querySelectorAll('#statInputs input').forEach(i=>s.stats[i.dataset.stat]=Math.max(0,Math.min(100,+i.value||0)));save();statsDialog.close();render()}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));
render();
